# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0004_program_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='Код сертификата')),
                ('is_active', models.BooleanField(default=False, verbose_name='Купон использован')),
                ('activation_date', models.DateTimeField(blank=True, verbose_name='Дата активации')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
    ]
