# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificate',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата активации'),
        ),
    ]
