# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0002_auto_20161109_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sertificate',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
    ]
