# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activation', '0003_auto_20161109_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
