# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код акции')),
                ('title', models.CharField(max_length=100, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(verbose_name='Программа действует')),
            ],
            options={
                'verbose_name_plural': 'Программы',
                'verbose_name': 'Программа',
            },
        ),
    ]
