# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20161104_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='programs.Category'),
            preserve_default=False,
        ),
    ]
