# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_program_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='photo',
            field=models.ImageField(default='', upload_to='images/programs/'),
            preserve_default=False,
        ),
    ]
